# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='levels',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
